#!/usr/bin/env python3
"""Render typed KID intent JSON into a _KID.ini file.

Pinned grammar is derived from powerof3 Keyword Item Distributor's current parser:
Keyword = keyword-or-form | target-type | filters | traits | chance
"""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path

TYPES={
"Armor","Weapon","Ammo","Magic Effect","Potion","Scroll","Location","Ingredient",
"Book","Misc Item","Key","Soul Gem","Spell","Activator","Flora","Furniture",
"Race","Talking Activator","Enchantment"
}

def ref(x:dict)->str:
    if x.get("editor_id"): return x["editor_id"]
    if x.get("form_id") and x.get("plugin"): return f'{x["form_id"]}~{x["plugin"]}'
    raise ValueError("KID keyword needs editor_id or form_id + plugin")

def render(e:dict)->str:
    if e.get("kind")!="KIDKeyword": raise ValueError("entry kind must be KIDKeyword")
    if e.get("target_type") not in TYPES: raise ValueError(f'unsupported KID target_type: {e.get("target_type")}')
    fields=[
      ref(e["keyword"]),
      e["target_type"],
      ",".join(e.get("filters",[])),
      e.get("traits","") or "",
      "" if e.get("chance") is None else str(e["chance"])
    ]
    while fields and fields[-1]=="": fields.pop()
    return "Keyword = "+"|".join(fields)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("intent",type=Path)
    ap.add_argument("--output",type=Path)
    ap.add_argument("--validate-only",action="store_true")
    args=ap.parse_args()
    data=json.loads(args.intent.read_text(encoding="utf-8"))
    if data.get("schema_version")!="skyrim-runtime-patch-intent-v1" or data.get("framework")!="kid":
        raise SystemExit("Expected skyrim-runtime-patch-intent-v1 with framework=kid")
    lines=["; Generated by Skyrim Mod Factory. Edit semantic intent, not this file.",
           f'; intent_id={data.get("intent_id","")}',
           f'; grammar_snapshot={data.get("grammar_source",{}).get("snapshot","")}','']
    errs=[]
    for i,e in enumerate(data.get("entries",[])):
        try:
            if e.get("comment"): lines.append("; "+e["comment"].replace("\n"," "))
            lines.append(render(e))
        except Exception as ex: errs.append(f"entry {i}: {ex}")
    if errs:
        print("\n".join(errs),file=sys.stderr); raise SystemExit(1)
    text="\n".join(lines)+"\n"
    if args.validate_only: print(text,end=""); return
    out=args.output or (Path(data["output_file"]) if data.get("output_file") else None)
    if out is None: raise SystemExit("Specify --output or output_file")
    if not out.name.lower().endswith("_kid.ini"): raise SystemExit("KID output filename must end with _KID.ini")
    out.parent.mkdir(parents=True,exist_ok=True); out.write_text(text,encoding="utf-8")
    print(out)

if __name__=="__main__": main()
