#!/usr/bin/env python3
"""Render source-verified BOS base-form swap intent into a _SWAP.ini file.

Supported here:
- [Forms] base -> swap rules
- [Forms|condition,...] conditional base -> swap rules
- base/swap sets
- raw property/chance fields passed to BOS's own parser

Reference/property-only sections are intentionally not generated yet.
"""
from __future__ import annotations
import argparse, collections, json, sys
from pathlib import Path

def ref(x:dict)->str:
    if x.get("editor_id"): return x["editor_id"]
    if x.get("form_id") and x.get("plugin"): return f'{x["form_id"]}~{x["plugin"]}'
    raise ValueError("BOS form needs editor_id or form_id + plugin")

def render_line(e:dict)->str:
    if e.get("kind")!="BOSFormSwap": raise ValueError("entry kind must be BOSFormSwap")
    bases=",".join(ref(x) for x in e.get("base",[]))
    swaps=",".join(ref(x) for x in e.get("swap",[]))
    if not bases or not swaps: raise ValueError("base and swap sets must be non-empty")
    fields=[bases,swaps,e.get("properties_raw","") or "",e.get("chance_raw","") or ""]
    while len(fields)>2 and fields[-1]=="": fields.pop()
    return "|".join(fields)

def section(e:dict)->str:
    cond=e.get("conditions") or []
    return "Forms" if not cond else "Forms|"+",".join(cond)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("intent",type=Path)
    ap.add_argument("--output",type=Path)
    ap.add_argument("--validate-only",action="store_true")
    args=ap.parse_args()
    data=json.loads(args.intent.read_text(encoding="utf-8"))
    if data.get("schema_version")!="skyrim-runtime-patch-intent-v1" or data.get("framework")!="bos":
        raise SystemExit("Expected skyrim-runtime-patch-intent-v1 with framework=bos")
    groups=collections.OrderedDict(); errs=[]
    for i,e in enumerate(data.get("entries",[])):
        try:
            groups.setdefault(section(e),[]).append((e,render_line(e)))
        except Exception as ex: errs.append(f"entry {i}: {ex}")
    if errs:
        print("\n".join(errs),file=sys.stderr); raise SystemExit(1)
    lines=["; Generated by Skyrim Mod Factory. Edit semantic intent, not this file.",
           f'; intent_id={data.get("intent_id","")}',
           f'; grammar_snapshot={data.get("grammar_source",{}).get("snapshot","")}','']
    for sec,items in groups.items():
        lines.append(f"[{sec}]")
        for e,line in items:
            if e.get("comment"): lines.append("; "+e["comment"].replace("\n"," "))
            lines.append(line)
        lines.append("")
    text="\n".join(lines).rstrip()+"\n"
    if args.validate_only: print(text,end=""); return
    out=args.output or (Path(data["output_file"]) if data.get("output_file") else None)
    if out is None: raise SystemExit("Specify --output or output_file")
    if not out.name.lower().endswith("_swap.ini"): raise SystemExit("BOS output filename must end with _SWAP.ini")
    out.parent.mkdir(parents=True,exist_ok=True); out.write_text(text,encoding="utf-8")
    print(out)

if __name__=="__main__": main()
