#!/usr/bin/env python3
"""Render typed SPID intent JSON into a _DISTR.ini file.

Grammar source currently pinned to powerof3's SPID Complete Reference.
Other runtime frameworks intentionally use separate renderers: do not reuse this
syntax for KID/BOS/FLM/SkyPatcher/OAR by analogy.
"""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path

SUPPORTED={"Spell","Perk","Item","Shout","Package","Keyword","Outfit","SleepOutfit","Faction","Skin","Form"}

def form_ref(x:dict)->str:
    if x.get("editor_id"):
        return x["editor_id"]
    if x.get("dynamic_keyword"):
        return x["dynamic_keyword"]
    if x.get("form_id") and x.get("plugin"):
        return f'{x["form_id"]}~{x["plugin"]}'
    raise ValueError("form must contain editor_id, dynamic_keyword, or form_id + plugin")

def field(exprs):
    if not exprs: return ""
    return ",".join(str(x) for x in exprs)

def chance_field(ch):
    if not ch: return ""
    val=ch["percent"]
    # avoid 60.0 noise when value is mathematically integral
    if isinstance(val,float) and val.is_integer():
        s=str(int(val))
    else:
        s=str(val)
    return s + ("!" if ch.get("deterministic",False) else "")

def render(entry:dict)->str:
    kind=entry["kind"]
    if kind not in SUPPORTED:
        raise ValueError(f"Unsupported SPID kind: {kind}")
    fields=[
      form_ref(entry["form"]),
      field(entry.get("string_filters")),
      field(entry.get("form_filters")),
      field(entry.get("level_filters")),
      entry.get("trait_filter","") or "",
      str(entry.get("count_or_package_index","")) if entry.get("count_or_package_index","") != "" else "",
      chance_field(entry.get("chance"))
    ]
    # SPID allows omitted optional tail sections. Trim only trailing blanks;
    # preserve interior separators because field position is semantic.
    while len(fields)>1 and fields[-1]=="":
        fields.pop()
    return f"{kind} = " + "|".join(fields)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("intent",type=Path)
    ap.add_argument("--output",type=Path)
    ap.add_argument("--validate-only",action="store_true")
    args=ap.parse_args()
    data=json.loads(args.intent.read_text(encoding="utf-8"))
    if data.get("schema_version")!="skyrim-runtime-patch-intent-v1":
        raise SystemExit("Wrong schema_version")
    if data.get("framework")!="spid":
        raise SystemExit("render_spid.py only accepts framework=spid")
    lines=[
      "; Generated by Skyrim Mod Factory. Edit the semantic intent JSON, not this file.",
      f'; intent_id={data.get("intent_id","")}',
      f'; grammar_snapshot={data.get("grammar_source",{}).get("snapshot","")}',
      ""
    ]
    errors=[]
    for i,e in enumerate(data.get("entries",[])):
        try:
            if e.get("comment"):
                lines.append("; "+e["comment"].replace("\n"," "))
            lines.append(render(e))
        except Exception as ex:
            errors.append(f"entry {i}: {ex}")
    if errors:
        print("\n".join(errors),file=sys.stderr)
        raise SystemExit(1)
    output="\n".join(lines)+"\n"
    if args.validate_only:
        print(output,end="")
        return
    out=args.output or (Path(data["output_file"]) if data.get("output_file") else None)
    if out is None:
        raise SystemExit("Specify --output or output_file in intent")
    if not out.name.lower().endswith("_distr.ini"):
        raise SystemExit("SPID output filename must end with _DISTR.ini")
    out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text(output,encoding="utf-8")
    print(f"Wrote {out}")

if __name__=="__main__":
    main()
